# Generated by Django 4.2.8 on 2023-12-22 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Bloq Şəkli')),
                ('post_date', models.DateField(verbose_name='Tarix')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('blog_desc', models.TextField(verbose_name='Bloq Təsviri')),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='Şərh sayı')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram URL')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook URL')),
                ('twitter', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter URL')),
                ('youtube', models.URLField(blank=True, max_length=255, null=True, verbose_name='YouTube URL')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug:')),
                ('likes_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog Postu',
                'verbose_name_plural': 'Bloq Postları',
            },
        ),
        migrations.CreateModel(
            name='BlogPostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=25, verbose_name='Kategoriya adı: ')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug:')),
            ],
            options={
                'verbose_name': 'Blog Post Kateqoriya',
                'verbose_name_plural': 'Blog Post Kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='BlogPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=25, verbose_name='Tag adı: ')),
            ],
            options={
                'verbose_name': 'Blog Post Tag',
                'verbose_name_plural': 'Blog Post Tagləri',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment_desc', models.TextField(verbose_name='Description')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('blogs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.blog', verbose_name='Blog')),
                ('user_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_users', to=settings.AUTH_USER_MODEL, verbose_name='User:')),
            ],
            options={
                'verbose_name': 'Commnet Post',
                'verbose_name_plural': 'Commnet Posts',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='category', to='blog.blogpostcategory', verbose_name='Kateqoriya:'),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', through='blog.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='product_tags', to='blog.blogposttag', verbose_name='Tag adı:'),
        ),
    ]
