# Generated by Django 4.2.8 on 2023-12-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_likes_alter_blog_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default=1, upload_to='blog/', verbose_name='Bloq Şəkli'),
            preserve_default=False,
        ),
    ]
