# Generated by Django 4.2.8 on 2023-12-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeyisebilenContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq ilk')),
                ('title_2', models.CharField(max_length=100, verbose_name='Başlıq sağ tərəf')),
                ('desc', models.CharField(max_length=100, verbose_name='Bizimlə əlaqə haqqında qısa məlumat')),
                ('phone', models.CharField(max_length=14, verbose_name='Əlaqə nömrəsi')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Şirkət E-poçtu')),
                ('unvan', models.CharField(max_length=100, verbose_name='Şirkət Ünvanı')),
            ],
            options={
                'verbose_name': 'Əlaqə səhifəsi dəyiş',
                'verbose_name_plural': 'Əlaqə səhifəsi dəyiş',
            },
        ),
    ]
