# Generated by Django 4.2.8 on 2023-12-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_deyisebilencontact_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeyisebilenHaqqimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq ilk')),
                ('title_2', models.CharField(max_length=255, verbose_name='Başlıq ikinci')),
                ('desc', models.CharField(max_length=255, verbose_name='Haqqımızda məlumat')),
            ],
            options={
                'verbose_name': 'Haqqımızda səhifəsi dəyiş',
                'verbose_name_plural': 'Haqqımızda səhifəsi dəyiş',
            },
        ),
    ]
