# Generated by Django 4.2.8 on 2023-12-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_deyisebilenhaqqimizda_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deyisebilenhaqqimizda',
            name='desc',
            field=models.TextField(verbose_name='Haqqımızda məlumat'),
        ),
    ]
