# Generated by Django 4.2.8 on 2023-12-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_deyisebilenhaqqimizda_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='deyisebilenhaqqimizda',
            name='image',
            field=models.ImageField(default=1, upload_to='haqqimizda/', verbose_name='Haqqımızda Şəkli'),
            preserve_default=False,
        ),
    ]
